[theme]
base="light"
primaryColor="#ff4fb7"
backgroundColor="#ffffff"
secondaryBackgroundColor="#ffe6f3"
textColor="#1f1f1f"
font="sans serif"

[server]
headless = true
enableXsrfProtection = true

[client]
showSidebarNavigation = true
